# Generated by Django 4.1.13 on 2024-05-19 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('applicant_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceField',
            fields=[
                ('experience_field_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantSkill',
            fields=[
                ('applicant_skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graficacion.applicant')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graficacion.skill')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantExperience',
            fields=[
                ('applicant_experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('years_of_experience', models.IntegerField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graficacion.applicant')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graficacion.company')),
                ('experience_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graficacion.experiencefield')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graficacion.position')),
            ],
        ),
    ]
